# ===============================
# DATABASE CONFIG (PostgreSQL Neon)
# ===============================

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}&channel_binding=${DB_CHANNEL_BINDING}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# HIKARI CONNECTION POOL
# ===============================

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# ===============================
# DISABLE H2 (IMPORTANT)
# ===============================

spring.h2.console.enabled=false

# ===============================
# SERVER CONFIG (optional)
# ===============================

server.port=8080